### ISSUE TITLE
Remote Notification Custom Payload

### ISSUE THREAD

**Issue by ghost** [vapor-community/onesignal#3]
The ability to add additional data to the remote notification payload is required. This will allow background update notifications so that apps running on iOS devices can refresh their data in the background. The current version of Vapor OneSignal supports the 'content-available' flag but doesn't support adding the respective additional content.

**Comment by ghost** [comment]
Just wondered if there has been any progress on this?

**Comment by Andrewangeta** [comment]
@david-canty
I believe this addresses your concern
https://github.com/vapor-community/onesignal/releases/tag/1.0.0-alpha.7

@anthonycastelli
